name: Build and Push Docker Image To AWS ECR
on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkoutname: Build and Push Docker Image To AWS ECR
on:
  push:
    branches:
      - main

jobs:
  build-push-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR
      run: |
        aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin ${{ secrets.ECR_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com

    - name: Build, tag, and push Docker image to Amazon ECR
      env:
        ECR_URI: ${{ secrets.ECR_ID }}.dkr.ecr.ap-northeast-2.amazonaws.com
        REPOSITORY: first-private-ecr
        IMAGE_TAG: latest
      run: |
        docker build -t $ECR_URI/$REPOSITORY:$IMAGE_TAG .
        docker tag $ECR_URI/$REPOSITORY:$IMAGE_TAG $ECR_URI/$REPOSITORY:$IMAGE_TAG
        docker push $ECR_URI/$REPOSITORY:$IMAGE_TAG

      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      
    - run: docker buildx build -t app .

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-northeast-2

    - name: Login to Amazon ECR Public
      id: login-ecr-public
      uses: aws-actions/amazon-ecr-login@v2
      with:
        registry-type: public

    - name: Build, tag, and push docker image to Amazon ECR Public
      env:
        REGISTRY: ${{ steps.login-ecr-public.outputs.registry }}
        REGISTRY_ALIAS: ${{ secrets.ECR_ID }}
        REPOSITORY: first-private-ecr
        IMAGE_TAG: latest
      run: |
        aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/${{ secrets.ECR_ID }}
        docker build -t $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG .
        docker push $REGISTRY/$REGISTRY_ALIAS/$REPOSITORY:$IMAGE_TAG
